### ISSUE TITLE
[Improvement] uiSref directives in ng2 components inside ng1

### ISSUE THREAD

**Issue by amcdnl** [ui-router/angular-hybrid#2]
Per my convo with @christopherthielen, this project does not allow you to have the ability to use ng2 ui-router directives inside a ng2 component that has been downgraded.
## Example

**bootstrap.js**

```
import { UpgradeAdapter } from '@angular/upgrade';
import { uiRouterNgUpgrade } from 'ui-router-ng1-to-ng2';

export const adapter = new UpgradeAdapter();
uiRouterNgUpgrade.setUpgradeAdapter(adapter);
```

**Component.js**

```
import { UIROUTER_DIRECTIVES } from 'ui-router-ng2';

@Component({
  selector: 'search',
  directives: [ UIROUTER_DIRECTIVES ]
})
export class Search {}
```

**module.js**

```
import angular from 'angular';
import { adapter } from '../adapter.js';

import { Search } from './Search.js';
import configState from './state.js';

export default angular
  .module('search', [])
  .config(configState)
  .directive('searchPage', adapter.downgradeNg2Component(Search))
```
## Results

Trying to do this results in the following error

```
"Error: DI Exception at NoProviderError.BaseException [as constructor] (http://localhost:8080/jspm_packages/npm/@angular/core@2.0.0-rc.1/src/facade/exceptions.js:17:23) at NoProviderError.AbstractProviderError [as constructor] (http://localhost:8080/jspm_packages/npm/@angular/core@2.0.0-rc.1/src/di/reflective_exceptions.js:39:16) at new NoProviderError (http://localhost:8080/jspm_packages/npm/@angular/core@2.0.0-rc.1/src/di/reflective_exceptions.js:75:16) at ReflectiveInjector_._throwOrNull (http://localhost:8080/jspm_packages/npm/@angular/core@2.0.0-rc.1/src/di/reflective_injector.js:776:19) at ReflectiveInjector_._getByKeyDefault (http://localhost:8080/jspm_packages/npm/@angular/core@2.0.0-rc.1/src/di/reflective_injector.js:804:25) at ReflectiveInjector_._getByKey (http://localhost:8080/jspm_packages/npm/@angular/core@2.0.0-rc.1/src/di/reflective_injector.js:767:25) at ReflectiveInjector_.get (http://localhost:8080/jspm_packages/npm/@angular/core@2.0.0-rc.1/src/di/reflective_injector.js:576:21) at ElementInjector.get (http://localhost:8080/jspm_packages/npm/@angular/core@2.0.0-rc.1/src/linker/element_injector.js:23:48) at DebugAppView._View_SearchPage0.createInternal (SearchPage.template.js:147:99) at DebugAppView.AppView.create (http://localhost:8080/jspm_packages/npm/@angular/core@2.0.0-rc.1/src/linker/view.js:66:21)"
```

**Comment by davidstellini** [comment]
Any updates?

**Comment by DzmVasileusky** [comment]
Ended with creating legacy directive for migration term.
```
import { Directive, Inject, Input, HostListener, OnInit } from '@angular/core';

@Directive({
    selector: '[uiSrefLegacy]'
})
export class UiSref implements OnInit {

    @Input() uiSrefLegacy: string;

    args: any = {};
    name: string;

    constructor (
        @Inject('$state') private $state: ng.ui.IStateService
    ) {}

    @HostListener('click', ['$event']) onClick (e: Event) {

        e.preventDefault();
        e.stopPropagation();
        this.$state.go(this.uiSref, this.args);

    }

    ngOnInit () {

        const destructed = this.uiSref.match(/(.*?)\(\{(.*?)\}\)|$/);
        this.name = destructed[1];

        if (destructed[2]) {

            const argsStr = destructed[2].replace(/ /g, '').split(',');
            argsStr.forEach((prop: string) => {

                const def = prop.split(':');
                this.args[def[0]] = def[1];

            });

        }

    }

}
```

**Comment by k0nG** [comment]
@DzmVasileusky thanks for that directive. I've updated it to work with `@angular/common@^7.2.2` and `@uirouter/angular-hybrid@6.0.3`

```typescript
import { Directive, Input, HostListener, OnInit } from '@angular/core';
import { StateService } from '@uirouter/core';

@Directive({
    selector: '[uiSrefLegacy]'
})
export class UiSref implements OnInit {

    @Input() uiSrefLegacy: string;

    args: any = {};
    name: string;

    constructor (
        private $state: StateService,
    ) {}

    @HostListener('click', ['$event']) onClick (e: Event) {
        e.preventDefault();
        e.stopPropagation();
        this.$state.go(this.uiSrefLegacy, this.args);
    }

    ngOnInit () {

        const destructed = this.uiSrefLegacy.match(/(.*?)\(\{(.*?)\}\)|$/);
        this.name = destructed[1];

        if (destructed[2]) {
            const argsStr = destructed[2].replace(/ /g, '').split(',');
            argsStr.forEach((prop: string) => {
                const def = prop.split(':');
                this.args[def[0]] = def[1];
            });
        }
    }
}

```
