### ISSUE TITLE
Error: State 'featureState1' is already defined

### ISSUE THREAD

**Issue by trumbitta** [ui-router/angular-hybrid#27]
Following the README, I:

- defined featureState1 in `$stateProvider`
- defined featureState1 in `feature.module.ts` via `UIRouterModule.forChild()`

When I point the browser to the URL set for `featureState1`, I get `Error: State 'featureState1' is already defined`.

If I remove `featureState1` from `$stateProvider`, the route doesn't exist and `$urlRouterProvider.otherwise('/')` gets me back to home.  
The same happens if I add the state to the main app module (also in the README) instead.

If I remove `UIRouterModule.forChild`, then I guess the case for a FeatureModule gets weakened.

Full error:

```
Error: State 'featureState1' is already defined
    at StateQueueManager.register (http://localhost:30300/vendor.js:88144:21) [<root>]
    at StateRegistry.register (http://localhost:30300/vendor.js:87726:34) [<root>]
    at http://localhost:30300/vendor.js:78936:70 [<root>]
    at Array.forEach (native) [<root>]
    at Object.applyModuleConfig (http://localhost:30300/vendor.js:78936:13) [<root>]
    at http://localhost:30300/vendor.js:106657:883 [<root>]
    at Array.forEach (native) [<root>]
    at n (http://localhost:30300/vendor.js:106657:854) [<root>]
    at DynamicNgUpgradeModuleInjector.get (/DynamicNgUpgradeModule/module.ngfactory.js:131:61) [<root>]
    at DynamicNgUpgradeModuleInjector.get (/DynamicNgUpgradeModule/module.ngfactory.js:166:92) [<root>]
    at DynamicNgUpgradeModuleInjector.getInternal (/DynamicNgUpgradeModule/module.ngfactory.js:407:54) [<root>]
    at DynamicNgUpgradeModuleInjector.NgModuleInjector.get (http://localhost:30300/vendor.js:20963:32) [<root>]
    at ReflectiveInjector_._getByKeyDefault (http://localhost:30300/vendor.js:17007:29) [<root>]
    at ReflectiveInjector_._getByKey (http://localhost:30300/vendor.js:16973:30) [<root>] <ui-view-ng-upgrade name="$default" class="ng-scope" id="NG2_UPGRADE_0_uiViewNgUpgrade_c0">
(anonymous) @ vendor.js:176647
(anonymous) @ vendor.js:173419
invokeLinkFn @ vendor.js:172970
nodeLinkFn @ vendor.js:172462
compositeLinkFn @ vendor.js:171858
publicLinkFn @ vendor.js:171738
(anonymous) @ vendor.js:90700
invokeLinkFn @ vendor.js:172968
nodeLinkFn @ vendor.js:172462
compositeLinkFn @ vendor.js:171858
publicLinkFn @ vendor.js:171738
updateView @ vendor.js:90613
configUpdatedCallback @ vendor.js:90570
configureUIView @ vendor.js:87514
ViewService.sync @ vendor.js:87516
activateViews @ vendor.js:87193
TransitionHook.invokeHook @ vendor.js:84551
TransitionHook.runSynchronousHooks @ vendor.js:84605
transitionSuccess @ vendor.js:84192
processQueue @ vendor.js:178919
(anonymous) @ vendor.js:178935
$eval @ vendor.js:180179
$digest @ vendor.js:179997
(anonymous) @ vendor.js:180218
completeOutstandingRequest @ vendor.js:169679
(anonymous) @ vendor.js:169956
ZoneDelegate.invokeTask @ polyfills.js:28677
Zone.runTask @ polyfills.js:28566
ZoneTask.invoke @ polyfills.js:28747
data.args.(anonymous function) @ polyfills.js:29564
```

**Comment by louwie17** [comment]
@trumbitta did you end up finding a fix for this bug? as I am encountering a similar bug, not sure if this is a hybrid app bug or if we are doing something wrong with entry components.

**Comment by trumbitta** [comment]
@louwie17 nope :-/ I'm waiting for good news by @christopherthielen about a new release of ng1-to-ng2 with "blessed" dependency versions

**Comment by christopherthielen** [comment]
hi @trumbitta @louwie17 [version 2.0.0 is now released](https://github.com/ui-router/angular-hybrid/releases/tag/2.0.0) and supports angular 4. 

As for feature modules, please see the sample app.  I just updated the preferences module to a feature module.  The contacts module is a lazy loaded feature module.

https://github.com/ui-router/sample-app-ng1-to-ng2

**Comment by parulprakash** [comment]
I am facing the same issue. what is the resolution?
