### ISSUE TITLE
Can't run example app

### ISSUE THREAD

**Issue by adamlubek** [ui-router/angular-hybrid#44]
hey, I downloaded the zip, opened git bash in examples folder then run 'npm install' -> 'npm start' and I'm getting:

```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'start' ]
2 info using npm@3.10.10
3 info using node@v6.9.5
4 verbose stack Error: missing script: start
4 verbose stack     at run (C:\Program Files\nodejs\node_modules\npm\lib\run-script.js:151:19)
4 verbose stack     at C:\Program Files\nodejs\node_modules\npm\lib\run-script.js:61:5
4 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:356:5
4 verbose stack     at checkBinReferences_ (C:\Program Files\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:320:45)
4 verbose stack     at final (C:\Program Files\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:354:3)
4 verbose stack     at then (C:\Program Files\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:124:5)
4 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:243:12
4 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\graceful-fs\graceful-fs.js:78:16
4 verbose stack     at tryToString (fs.js:455:3)
4 verbose stack     at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:442:12)
5 verbose cwd C:\angular-hybrid-master
6 error Windows_NT 10.0.14393
7 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
8 error node v6.9.5
9 error npm  v3.10.10
10 error missing script: start
11 error If you need help, you may report this error at:
11 error     <https://github.com/npm/npm/issues>
12 verbose exit [ 1, true ]
```

am I missing something to run this?

**Comment by uazure** [comment]
It seems like you are trying to start example app not from the `example` directory.
Consider going to `example` directory and do `npm i` and then `npm start`

**Comment by adamlubek** [comment]
First sentence I wrote was "hey, I downloaded the zip, opened git bash **in examples folder** then run 'npm install' -> 'npm start'" ;)

anyway, tried again (in both examples and root folders), the same problem.

**Comment by uazure** [comment]
The error you posted says that there's no `start` script defined in package.json that npm used to perform `npm start`.
BTW, I also can't run the example app because of another error related to missing webpack configuration file
```
SergiiP@CP003 MINGW64 ~/dev/angular-hybrid/example (master)
$ npm start

> @ start C:\Users\SergiiP\dev\angular-hybrid\example
> webpack-dev-server --open

No configuration file found and no entry configured via CLI option.
When using the CLI you need to provide at least two arguments: entry and output.
A configuration file could be named 'webpack.config.js' in the current directory                                                                                            .
Use --help to display the CLI options.

npm ERR! Windows_NT 10.0.15063
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\                                                                                            node_modules\\npm\\bin\\npm-cli.js" "start"
npm ERR! node v6.11.0
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! @ start: `webpack-dev-server --open`
npm ERR! Exit status 4294967295
npm ERR!
npm ERR! Failed at the @ start script 'webpack-dev-server --open'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the  package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     webpack-dev-server --open
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\SergiiP\dev\angular-hybrid\example\npm-debug.log

```

**Comment by adamlubek** [comment]
I posted wrong stack trace, silly me! yeah, I'm getting the same errors you've pasted.

**Comment by christopherthielen** [comment]
I had a git ignore for `*.js` to ignore transpiled files, whoops!   I've force added the webpack config file.  Should be working now!

**Comment by christopherthielen** [comment]
a606d26d9e835f87527ef6cf50b21389e63ce23c 854861784d13c644ecae8a5efe5991b70782f8f9
