### ISSUE TITLE
Angular Hybrid application bootstrapping fails with Protractor 

### ISSUE THREAD

**Issue by balazshc** [ui-router/angular-hybrid#45]
I tried to test an Angular-Hybrid application with Protractor, but bootstrapping fails. 
After that I tried to test the Sample Angular-Hybrid application with Protractor, but it failed with the same error:
 <pre>
Unhandled Promise rejection: Cannot read property 'get' of undefined ; Zone: <root> ; Task: Promise.then ; Value: TypeError: Cannot read property 'get' of undefined
    at Object.getUIRouter (angular-hybrid.js:138)
    at SampleAppModuleAngularInjector.get [as __uiRouter_37] (angularModule.ngfactory.ts:191)
    at SampleAppModuleAngularInjector.get [as _UIRouter_38] (angularModule.ngfactory.ts:195)
    at SampleAppModuleAngularInjector.getInternal (angularModule.ngfactory.ts:346)
    at SampleAppModuleAngularInjector.NgModuleInjector.get (core.es5.js:3577)
    at main.ts:51
    at ZoneDelegate.invoke (zone.js:391)
    at Zone.run (zone.js:141)
    at zone.js:818
    at ZoneDelegate.invokeTask (zone.js:424) TypeError: Cannot read property 'get' of undefined
    at Object.getUIRouter (https://ui-router.github.io/sample-app-angular-hybrid/_bundles/sampleapp.js:448:21)
    at SampleAppModuleAngularInjector.get [as __uiRouter_37] (https://ui-router.github.io/sample-app-angular-hybrid/_bundles/sampleapp.js:867:48)
    at SampleAppModuleAngularInjector.get [as _UIRouter_38] (https://ui-router.github.io/sample-app-angular-hybrid/_bundles/sampleapp.js:877:74)
    at SampleAppModuleAngularInjector.getInternal (https://ui-router.github.io/sample-app-angular-hybrid/_bundles/sampleapp.js:1184:24)
    at SampleAppModuleAngularInjector.NgModuleInjector.get (https://ui-router.github.io/sample-app-angular-hybrid/_bundles/vendor.bundle.js:4928:44)
    at https://ui-router.github.io/sample-app-angular-hybrid/_bundles/sampleapp.js:2444:24
    at ZoneDelegate.invoke (https://ui-router.github.io/sample-app-angular-hybrid/_bundles/vendor.bundle.js:52243:26)
    at Zone.run (https://ui-router.github.io/sample-app-angular-hybrid/_bundles/vendor.bundle.js:51993:43)
    at https://ui-router.github.io/sample-app-angular-hybrid/_bundles/vendor.bundle.js:52670:57
    at ZoneDelegate.invokeTask (https://ui-router.github.io/sample-app-angular-hybrid/_bundles/vendor.bundle.js:52276:31)
</pre>

Sample Protractor config to reproduce the problem:

- Protractor version 5.1.2
- webdriver-manager version 12.0.6

<i>config.js</i>:
```JavaScript
exports.config = {
  //The address of a running selenium server.
  seleniumAddress: 'http://localhost:4444/wd/hub',
  //Here we specify the name of the specs files.
  specs: ['testspec.js']
}
```
<i>testspec.js</i>
```JavaScript
describe('angularjs homepage', function() {
  it('should have a title', function() {
    browser.get('https://ui-router.github.io/sample-app-angular-hybrid/#!/mymessages/inbox/5648b50d5d8be25776881a3f');

    browser.wait(function() {
      return $('.container').isPresent(); // keeps waiting until this statement resolves to true
    }).catch( () => {
    	browser.pause();
    });
  });
});
```

**Comment by balazshc** [comment]
Found a workaround in a closed issue: https://github.com/ui-router/angular-hybrid/issues/39
