### ISSUE TITLE
Failure to inject $transition$ into a downgraded ng2 component

### ISSUE THREAD

**Issue by alcroito** [ui-router/angular-hybrid#577]
Hi,

I've encountered an issue where `$transition$` can't be injected into a downgraded ng2 component constructor, when not using any resolve function.

The relevant bit of code:
```
@Component({
  selector: 'ng2-component',
  template: `
    <h1>ng2 component</h1>
  `,
})
export class Ng2Component {
  constructor(
    @Inject('$transition$') $transition$: Transition,
  ) {
    console.log('>>> $transition$', $transition$)

  }
}

app
    .directive(
        "ng2Component",
        downgradeComponent({ component: Ng2Component }) as angular.IDirectiveFactory
    );

    $stateRegistry.register({
      url: '/ng2',
      name: 'app.ng1.ng2',
      component: 'ng2Component',
    });
```

Note that `component` is specified as a string rather than a class name.
If I change 
```
      component: 'ng2Component',
```
to
```
      component: Ng2Component,
```

Injection succeeds.
It also succeeds for non-downgraded ng1 components declared via `app.component()`.
So the error only seems to affect downgraded ng2 components.
I also tried variations like `transition` instead `$transition` to no success.

The error is 
```
angular.js:14525 NullInjectorError: R3InjectorError(RootModule)[$transition$ -> $transition$ -> $transition$]: 
  NullInjectorError: No provider for $transition$!
    at NullInjector.get (core.mjs:6359:1)
    at R3Injector.get (core.mjs:6786:1)
    at R3Injector.get (core.mjs:6786:1)
    at R3Injector.get (core.mjs:6786:1)
    at ChainedInjector.get (core.mjs:13769:1)
    at lookupTokenUsingModuleInjector (core.mjs:3293:1)
    at getOrCreateInjectable (core.mjs:3338:1)
    at ɵɵdirectiveInject (core.mjs:10871:1)
    at NodeInjectorFactory.Ng2Component_Factory [as factory] (ɵfac.js? [sm]:1:1)
    at getNodeInjectable (core.mjs:3523:1) '<ng2-component class="ng-scope" ng-version="14.2.5">'
```

Is this not supported, or am I doing something wrong?
I would like to use downgraded ng2 components in the router until i've ported everything to remove the usage of the hybrid router.

Providing full reproducer `main.ts` that can be replaced into the `example/src/main.ts` file of the repo.

```
import * as angular from 'angular';
import { Component, NgModule, NgZone, Inject } from '@angular/core';
import { platformBrowserDynamic } from '@angular/platform-browser-dynamic';
import { UpgradeModule, downgradeComponent } from '@angular/upgrade/static';
import { BrowserModule } from '@angular/platform-browser';
import { UIRouterUpgradeModule, NgHybridStateDeclaration } from '@uirouter/angular-hybrid';
import { UrlService, Transition } from '@uirouter/core';

const app = angular.module('minimal', ['ui.router.upgrade']);

app.run([
  '$stateRegistry',
  '$urlService',
  ($stateRegistry, $urlService) => {
    $urlService.rules.initial({ state: 'app' });

    $stateRegistry.register({
      url: '',
      name: 'app',
      template: `
        <a ui-sref=".ng1" ui-sref-active-eq="active">app.ng1</a>
        <a ui-sref=".ng1.ng2" ui-sref-active-eq="active">app.ng1.ng2</a>
        <a ui-sref=".ng2" ui-sref-active-eq="active">app.ng2</a>
        <a ui-sref=".ng2.ng2" ui-sref-active-eq="active">app.ng2.ng2</a>
        <ui-view></ui-view>
      `,
    });

    // route to ng1 component
    $stateRegistry.register({
      url: '/ng1',
      name: 'app.ng1',
      component: 'ng1Component',
    });

    // nested route to ng2 component
    $stateRegistry.register({
      url: '/ng2',
      name: 'app.ng1.ng2',
      // component: Ng2Component,
      component: 'ng2Component',
    });

    // route to ng2 component
    $stateRegistry.register({
      url: '/ng2',
      name: 'app.ng2',
      // component: Ng2Component,
      component: 'ng2Component',
    });
  },
]);

// An AngularJS component
app.component('ng1Component', {
  template: `
      <h1>ng1 component</h1>
      <a ui-sref="app">Back to app</a>
      <ui-view></ui-view>
    `,
  controller: function () {
    this.$onInit = function () {
      console.log('ng1Component.$onInit()');
    };
  },
});

// An Angular component
@Component({
  selector: 'ng2-component',
  template: `
    <h1>ng2 component</h1>
    <a uiSref="app">Back to app</a>
    <ui-view></ui-view>
  `,
})
export class Ng2Component {
  constructor(
    @Inject('$transition$') $transition$: Transition,
  ) {
    console.log('>>> $transition$', $transition$)

  }
  ngOnInit() {
    console.log('Ng2Component.ngOnInit()');
  }
}

app
    .directive(
        "ng2Component",
        downgradeComponent({ component: Ng2Component }) as angular.IDirectiveFactory
    );

const nestedState: NgHybridStateDeclaration = {
  url: '/ng2',
  name: 'app.ng2.ng2',
  component: Ng2Component,
};

// The root Angular module
@NgModule({
  imports: [
    BrowserModule,
    // Provide Angular upgrade capabilities
    UpgradeModule,
    // Provides the @uirouter/angular directives
    UIRouterUpgradeModule.forRoot({ states: [nestedState] }),
  ],
  declarations: [Ng2Component],
  entryComponents: [Ng2Component],
})
export class RootModule {
  constructor(private upgrade: UpgradeModule) {}
  ngDoBootstrap() {
    // The DOM must be already be available
    this.upgrade.bootstrap(document.body, [app.name]);
  }
}

// Using AngularJS config block, call `deferIntercept()`.
// This tells UI-Router to delay the initial URL sync (until all bootstrapping is complete)
app.config(['$urlServiceProvider', ($urlService) => $urlService.deferIntercept()]);

// Manually bootstrap the Angular app
platformBrowserDynamic()
  .bootstrapModule(RootModule)
  .then((platformRef) => {
    // get() UrlService from DI (this call will create all the UIRouter services)
    const url: UrlService = platformRef.injector.get(UrlService);

    // Instruct UIRouter to listen to URL changes
    function startUIRouter() {
      url.listen();
      url.sync();
    }

    const ngZone: NgZone = platformRef.injector.get(NgZone);
    ngZone.run(startUIRouter);
  });

```

**Comment by wawyed** [comment]
Can you  not simply do `transition: Transition` without the @Inject. I didn't think that was necessary

**Comment by alcroito** [comment]
It fails in the same way.
```
angular.js:14525 NullInjectorError: R3InjectorError(RootModule)[Transition -> Transition -> Transition]: 
  NullInjectorError: No provider for Transition!
    at NullInjector.get (core.mjs:6359:1)
    at R3Injector.get (core.mjs:6786:1)
    at R3Injector.get (core.mjs:6786:1)
    at R3Injector.get (core.mjs:6786:1)
    at ChainedInjector.get (core.mjs:13769:1)
    at lookupTokenUsingModuleInjector (core.mjs:3293:1)
    at getOrCreateInjectable (core.mjs:3338:1)
    at ɵɵdirectiveInject (core.mjs:10871:1)
    at NodeInjectorFactory.Ng2Component_Factory [as factory] (ɵfac.js? [sm]:1:1)
    at getNodeInjectable (core.mjs:3523:1) '<ng2-component class="ng-scope" ng-version="14.2.5">'
(anonymous) @ angular.js:14525
(anonymous) @ angular.js:11008
invokeLinkFn @ angular.js:10428
nodeLinkFn @ angular.js:9815
compositeLinkFn @ angular.js:9055
publicLinkFn @ angular.js:8920
(anonymous) @ viewDirective.js:350
(anonymous) @ angular.js:1346
invokeLinkFn @ angular.js:10426
nodeLinkFn @ angular.js:9815
compositeLinkFn @ angular.js:9055
publicLinkFn @ angular.js:8920
lazyCompilation @ angular.js:9311
updateView @ viewDirective.js:257
configUpdatedCallback @ viewDirective.js:201
configureUIView @ view.js:149
ViewService.sync @ view.js:157
ViewService.registerUIView @ view.js:184
(anonymous) @ viewDirective.js:205
(anonymous) @ angular.js:1346
invokeLinkFn @ angular.js:10426
nodeLinkFn @ angular.js:9815
compositeLinkFn @ angular.js:9055
nodeLinkFn @ angular.js:9809
compositeLinkFn @ angular.js:9055
publicLinkFn @ angular.js:8920
(anonymous) @ viewDirective.js:350
(anonymous) @ angular.js:1346
invokeLinkFn @ angular.js:10426
nodeLinkFn @ angular.js:9815
compositeLinkFn @ angular.js:9055
publicLinkFn @ angular.js:8920
lazyCompilation @ angular.js:9311
updateView @ viewDirective.js:257
configUpdatedCallback @ viewDirective.js:201
configureUIView @ view.js:149
ViewService.sync @ view.js:157
activateViews @ views.js:39
invokeCallback @ transitionHook.js:90
TransitionHook.invokeHook @ transitionHook.js:95
(anonymous) @ transitionHook.js:75
TransitionHook.runAllHooks @ transitionHook.js:75
transitionSuccess @ transition.js:575
processQueue @ angular.js:16832
(anonymous) @ angular.js:16876
$digest @ angular.js:17971
$apply @ angular.js:18269
(anonymous) @ angular.js:20186
completeOutstandingRequest @ angular.js:6274
(anonymous) @ angular.js:6554
timer @ zone.js:3155
_ZoneDelegate.invokeTask @ zone.js:443
onInvokeTask @ core.mjs:26218
_ZoneDelegate.invokeTask @ zone.js:442
Zone.runTask @ zone.js:214
ZoneTask.invokeTask @ zone.js:525
ZoneTask.invoke @ zone.js:514
data.args.<computed> @ zone.js:3135
setTimeout (async)
scheduleTask @ zone.js:3137
_ZoneDelegate.scheduleTask @ zone.js:430
onScheduleTask @ zone.js:320
_ZoneDelegate.scheduleTask @ zone.js:423
Zone.scheduleTask @ zone.js:257
Zone.scheduleMacroTask @ zone.js:280
scheduleMacroTaskWithCurrentZone @ zone.js:729
(anonymous) @ zone.js:3179
proto.<computed> @ zone.js:1022
Browser.self.defer @ angular.js:6552
timeout @ angular.js:20176
(anonymous) @ stateDirectives.js:53
defaultHandlerWrapper @ angular.js:3734
eventHandler @ angular.js:3722
_ZoneDelegate.invokeTask @ zone.js:443
onInvokeTask @ core.mjs:26218
_ZoneDelegate.invokeTask @ zone.js:442
Zone.runTask @ zone.js:214
ZoneTask.invokeTask @ zone.js:525
invokeTask @ zone.js:1727
globalCallback @ zone.js:1758
globalZoneAwareCallback @ zone.js:1794
```

**Comment by wawyed** [comment]
I'm a little bit confused because Transition refers to the current transition in progress. When the component is loaded the transition is finsihed so it shouldn't exsist. What are you trying to use Transition for?

**Comment by alcroito** [comment]
Is the transition finished by the time the component constructor is called?

The documentation at https://ui-router.github.io/ng1/docs/latest/modules/injectables.html#_stateparams
states that when $stateParams is injected into view controllers, it is the current per-transition object, not a finished / successful transition.

Quote
```
When injected into transition hooks, resolves, or view controllers, the object is the Per-Transition Object with the parameter values for the running Transition.
```

And the deprecation replacement code suggests injecting it like that into a view controller.
And by extension, I hoped the same would work for downgraded ng2 components.

> What are you trying to use Transition for?
I'd like to get the transition to get the params() associated with it.

**Comment by wawyed** [comment]
I don't see any issue with you using `StateService.params` (or `UIRouterGlobals.params`) .... Also from checking the (angular code) the component gets instantiated when the transition is successful, so you shouldn't have to access or rely on Transition.

In relation to the link you send, there was some problems in AngularJS with relying on $stateParams thats why it's encouraged to move away from it. But you shouldn't have any issues with StateService.params o UIRouterGlobals.params when used inside a uiview Component

**Comment by alcroito** [comment]
I see.

But then at what point is the ongoing transition object available? Only in resolve functions and transition hooks?

**Comment by wawyed** [comment]
> I see.
> 
> But then at what point is the ongoing transition object available? Only in resolve functions and transition hooks?

Exactly :). Only when a transition is in progress you should look at the transition object

**Comment by alcroito** [comment]
Ok, thank you for your help!

I'm still curious why the $transitition$ object is conditionally available in the constructor depending on the component type, but it's not that critical anymore.

**Comment by wawyed** [comment]
> Ok, thank you for your help!
> 
> I'm still curious why the `$transition$` object is conditionally available in the constructor depending on the component type, but it's not that critical anymore.

No worries, I'm trying to get the example repo running to see If I can have a look but as I said I wouldn't rely on the Transition object being available inside a component constructor.

Take into account that a Transition object only makes sense during a state change/transition and once the Transition is completed it becomes obsolete and any changes to the state would incur in a new Transition object being created.
